services:
  rust-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - cargo-cache:/usr/local/cargo/registry
    working_dir: /usr/src/app
    # command: cargo run
    stdin_open: true
    tty: true

volumes:
  cargo-cache:
